dataset:
  name: "Toys_and_Games"
  max_items_per_seq: 128
  type: "AmazonReviews2014"
  features_needed: ["title", "brand", "categories"]
  prompt_format: "v1"

data_processing:
  use_unified_embeddings: true
  cache_dir: "cache"
  metadata: "sentence"
  sent_emb_model: "text-embedding-3-large"
  sent_emb_dim: 3072
  sent_emb_batch_size: 1024
  sent_emb_pca: 512 
  faiss_omp_num_threads: 16
  opq_use_gpu: false
  opq_gpu_id: 0
  openai_api_key: sk-492a02uVsAauNrYsP4YRW2pvAsELc20hoHJeUh2Sop3GiL3C
  openai_base_url: https://yunwu.ai/v1

RQ-VAE:
  input_dim: 512 
  hidden_dim: [1024, 512]
  latent_dim: 256
  num_layers: 3
  code_book_size: 2048  
  dropout: 0.0
  beta: 0.25            
  epochs: 3000          
  batch_size: 8192
  optimizer: "AdamW"
  lr: 0.001
  weight_decay: 0.0

training:
  device: "cuda:0"

MoE-Training:
  lr: 1.0e-4
  epochs: 50
  batch_size: 256
  num_experts: 2
  load_balancing_alpha: 0.01

FinalQuantizer:
  lr: 2.0e-4
  epochs: 100
  batch_size: 512
  beta: 0.25
  hidden_sizes: [64]